# Generated by Django 4.1.7 on 2024-05-16 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technologies', models.CharField(choices=[('HTML/CSS', 'HTML/CSS'), ('PHP', 'PHP'), ('JS', 'JavaScript'), ('PYTHON', 'Python'), ('VUE', 'Vue.js'), ('NODE', 'Node.js'), ('SYMFONY', 'Symfony')], max_length=50)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('project_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='blog.category')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='blog/images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('language', models.CharField(choices=[('PHP', 'PHP'), ('JS', 'JavaScript'), ('PYTHON', 'Python'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('JAVA', 'java')], max_length=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.category')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='')),
                ('public', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='blog.category')),
            ],
        ),
    ]
