# Generated by Django 5.0.6 on 2024-06-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
