# Generated by Django 5.0.6 on 2024-06-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_project_image_project_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_path',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
