# Generated by Django 5.0.6 on 2024-06-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_project_image_path_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='new',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
