# Generated by Django 5.0.6 on 2024-06-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_framwork_remove_project_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='framework',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Framwork',
        ),
    ]
