# Generated by Django 5.0.6 on 2024-06-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_project_framework_delete_framwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='framework',
            field=models.CharField(choices=[('Vue.js', 'Vuejs'), ('Nodes.js', 'Nodesjs'), ('Symfony', 'Symphony'), ('Django', 'Django')], max_length=10),
        ),
    ]
