# Generated by Django 5.0.6 on 2024-06-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_project_framework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='framework',
        ),
        migrations.AddField(
            model_name='project',
            name='frameworkback',
            field=models.CharField(choices=[('Nodes.js', 'Nodesjs'), ('Symfony', 'Symphony'), ('Django', 'Django')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='frameworkfront',
            field=models.CharField(choices=[('Vue.js', 'Vuejs')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
