# Generated by Django 5.0.6 on 2024-06-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_project_framework_project_frameworkback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='frameworkback',
            field=models.CharField(blank=True, choices=[('Nodes.js', 'Nodesjs'), ('Symfony', 'Symphony'), ('Django', 'Django')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='frameworkfront',
            field=models.CharField(blank=True, choices=[('Vue.js', 'Vuejs')], max_length=10, null=True),
        ),
    ]
